services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules # Prevent overwriting node_modules with host's empty directory
    networks:
      - app-network
    depends_on:
      - backend
      - mysql
  
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: NewStrongRootPassword!123
      MYSQL_DATABASE: whackathon
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge